Update new reset password flow
bitholla/hollaex-tools-lib pull request #50
Opened 2021-07-29 03:29 UTC by hoan-bitholla

2021-07-29 04:45 UTC, brandonkimmmm commented on tools/security.js
>  		.then((user) => user.update({ password: newPassword }, { fields: ['password'] }));
We can use bluebird all here to run `client.delAsync` and `dbQuery.findOne(...` at the same time. If `client.delAsync` fails, the function will throw an error.

```
    return all([
        dbQuery.findOne('user', { where: { id: user_id } }),
        client.delAsync(`ResetPasswordCode:${resetPasswordCode}`)
    ])
})
.then(([ user ]) => {
    ...
})
```

2021-07-29 05:07 UTC, abeikverdi commented on tools/security.js
> +	const setCode = client.setex(resetPasswordCodeKey, 60 * 60 * 24, newCode);
This should be shorter. set it to 5 mins.

2021-07-29 09:06 UTC, abeikverdi commented on tools/security.js
>  			return code;
you dont need to add a catch here. this promise should be caught in a higher level call. Follow the rest of the code. A simple return is sufficient here. Also double check redis to make sure it actually expires @hoan-bitholla

2021-08-03 04:21 UTC, brandonkimmmm requested changes

2021-08-03 04:28 UTC, hoan-bitholla commented on tools/security.js
> +		});
I removed it in previous commit

2021-08-03 04:31 UTC, hoan-bitholla commented on tools/security.js
> +				// client.delAsync(`ChangePasswordCode:${code}`)
This code is outdated! I fixed it!

2021-08-03 04:34 UTC, hoan-bitholla commented on tools/security.js
> +			return user_id;
I renamed

2021-08-03 04:36 UTC, hoan-bitholla commented on tools/security.js
> +		})
Because Ali want to double check redis to make sure it acctually expires, so I get TTL of key

2021-08-03 04:53 UTC, brandonkimmmm approved these changes

2021-08-03 04:53 UTC, merged